<h1 
    class="text-center w-full rf-2xl pb-0 font-ws text-primary/75 font-bold mb-6 pt-4"
>
    <?= $title ?>
</h1>

<div class="mt-4 mx-2 mb-28">
    <?php foreach($goods as $good): ?>
        <div class="card mb-8">
            <div class="card-header bg-secondary">
                <h2 class="card-title text-white"><?= $good->description ?></h2>
            </div>
            <div class="card-body">
                <p id="snackbar-card-<?= $good->id ?>" class="card-content rf-lg font-bold text-secondary text-center">
                <?= price_format(value: $good->price) ?>
                </p>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<button id="refresh-data" class="btn-round bg-primary text-white fixed bottom-8 left-8">
    <i class="fa-solid fa-arrows-rotate"></i>
</button>