services:
  web:
    image: php:8.3.4-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www/
    depends_on:
      - server
    networks:
      - project-network

  server:
    image: nginx:mainline
    container_name: nginx
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project-network

  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: manager
      MYSQL_DATABASE: restaurant
      # For development environments only
      MYSQL_PASSWORD: databasepassword
      MYSQL_ROOT_PASSWORD: rootdatabasepassword
      # -----------------------------------------
    volumes:
      - /etc/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - project-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_USER: manager
      MYSQL_DATABASE: restaurant
      # For development environments only
      MYSQL_PASSWORD: databasepassword
      MYSQL_ROOT_PASSWORD: rootdatabasepassword
      # -----------------------------------------
      PMA_HOST: mysql
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
