<div class="background">
    <form action="/" method="POST">
        <div>
            <label for="user_email" class="teste">Email</label>
            <input id="user_email" type="email" name="user[email]" class="form-control">
        </div>
        <div>
            <label for="user_password" class="form-label">Senha</label>
            <input id="user_password" type="password" name="user[password]" class="form-control">
        </div>
        <div>
            <input type="submit"value="Logar">
        </div>
    </form>
</div>