<main class="w-11/12 m-auto">
    <h1 
        class="text-center w-full rf-2xl pb-0 font-ws text-primary/75 font-bold mb-6 pt-4"
    >
        <?= $title ?>
    </h1>

    <section class="flex flex-col justify-center items-center">
        <h2 class="text-center w-full rf-xl font-ws text-primary/75 font-semibold">Fazer reserva</h2>
        <div class="flex flex-col gap-6 mt-4 w-full m-auto">
            <?php if(!$lunchReservation): ?>
                <form 
                    action="<?= Route(name: 'user.reservation.create', params: ['mealId' => $mealIds['lunchId']]) ?>"
                    method="POST"
                class="w-full"
                >
                    <button class="flex gap-1 w-full" type="submit">
                        <div class="bg-secondary rounded-l-2xl h-12 flex items-center justify-center text-white font-semibold w-full">Almoço</div>
                    
                        <div class="bg-white rounded-none rounded-r-2xl
                        h-12 flex items-center justify-center text-secondary font-semibold border-secondary border-solid border-2 w-full">Confirmar</div>
                    </button>
                </form>

            <?php else: ?>

                <form 
                    action="<?= Route(name: 'user.reservation.destroy', params: ['mealId' => $mealIds['lunchId']]) ?>"
                    method="POST"
                    class="w-full"
                >
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="flex gap-1 w-full" type="submit">
                        <div class="bg-secondary rounded-l-2xl h-12 flex items-center justify-center text-white font-semibold w-full">Almoço</div>
                    
                        <div class="bg-secondary/75 rounded-none rounded-r-2xl
                        h-12 flex items-center justify-center text-white font-semibold border-secondary border-solid border-2 w-full">Confirmado</div>
                    </button>
                </form>
            <?php endif; ?>

            <?php if(!$dinnerReservation): ?>
                <form 
                    action="<?= Route(name: 'user.reservation.create', params: ['mealId' => $mealIds['dinnerId']]) ?>"
                    method="POST"
                class="w-full"
                >
                    <button class="flex gap-1 w-full" type="submit">
                        <div class="bg-secondary rounded-l-2xl h-12 flex items-center justify-center text-white font-semibold w-full">Janta</div>
                    
                        <div class="bg-white rounded-none rounded-r-2xl
                        h-12 flex items-center justify-center text-secondary font-semibold border-secondary border-solid border-2 w-full">Confirmar</div>
                    </button>
                </form>

            <?php else: ?>
                
                <form 
                    action="<?= Route(name: 'user.reservation.destroy', params: ['mealId' => $mealIds['dinnerId']]) ?>"
                    method="POST"
                    class="w-full"
                >
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="flex gap-1 w-full" type="submit">
                        <div class="bg-secondary rounded-l-2xl h-12 flex items-center justify-center text-white font-semibold w-full">Janta</div>
                    
                        <div class="bg-secondary/75 rounded-none rounded-r-2xl
                        h-12 flex items-center justify-center text-white font-semibold border-secondary border-solid border-2 w-full">Confirmado</div>
                    </button>
                </form>
            <?php endif; ?>

        </div>
    </section>
</main>