<div class="flex items-end justify-center w-full h-[85%]">
    <div class="mb-20">
        <main 
            class="flex flex-col gap-12"
        >
            <a 
                type="button"
                href="<?= Route(name: 'user.reservations') ?>" 
                class="btn-lg bg-primary"
            >
                Reservas
            </a>

            <a 
                type="button"
                href="<?= Route(name: 'snackbar') ?>" 
                class="btn-lg bg-primary"
            >
                Cantina
            </a>

            <button type="button" class="btn-lg bg-primary text-white">Cardápio</button>
        </main>
    </div>
</div>