<div class="flex items-end justify-center w-full h-[85%]">
    <div class="mb-20">
        <main 
            class="flex flex-col gap-12"
        >
            <button type="button" class="btn-lg bg-primary hover:scale-105 transition-all text-white">Agendar Refeição</button>
            <button type="button" class="btn-lg bg-primary hover:scale-105 transition-all text-white">Cardápio</button>
        </main>
    </div>
</div>