<?php

use Core\Router\Route;
?>
<form 
    action="<?= Route(name: 'user.feedbacks.create') ?>"
    method="POST"
    class="text-white"
>
    <div>
        <label for="feedback-type-complaint">Complaint</label>
        <input type="radio" name="feedback[type]" id="feedback-type-complaint" value="complaint">
        <label for="feedback-type-compliment">compliment</label>
        <input type="radio" name="feedback[type]" id="feedback-type-compliment" value="compliment">
        <label for="feedback-type-question">question</label>
        <input type="radio" name="feedback[type]" id="feedback-type-question" value="question">
        <label for="feedback-type-suggestion">suggestion</label>
        <input type="radio" name="feedback[type]" id="feedback-type-suggestion" value="suggestion">
    </div>

    <div>
        <label for="rating-one">1</label>
        <input type="radio" name="feedback[rating]" id="rating-one" value="1">

        <label for="rating-two">2</label>
        <input type="radio" name="feedback[rating]" id="rating-two" value="2">

        <label for="rating-three">3</label>
        <input type="radio" name="feedback[rating]" id="rating-three" value="3">

        <label for="rating-four">4</label>
        <input type="radio" name="feedback[rating]" id="rating-four" value="4">

        <label for="rating-five">5</label>
        <input type="radio" name="feedback[rating]" id="rating-five" value="5">
    </div>

    <div>
        <textarea name="message[content]" id="message_content"></textarea>
    </div>

    <div>
        <label for="is-harmfull-yes">Sim</label>
        <input type="radio" name="feedback[is_harmfull]" id="is-harmfull-yes" value="1">

        <label for="is-harmfull-no">Não</label>
        <input type="radio" name="feedback[is_harmfull]" id="is-harmfull-no" value="0">
    </div>

    <button type="submit">CRIAR</button>

</form>