<form
    action="<?= route('user.feedbacks.update', ['id' => $paramId]) ?>" method="POST" class="flex flex-col gap-8 items-start w-1/2 mx-auto min-h-screen text-white">
    <input type="hidden" name="_method" value="PUT">

    <div>
        <h3 class="text-xl">Tipo *</h3>
        <select name="feedback[type]" class="bg-tertiary w-48 h-9 rounded px-2">
            <option value="complaint" <?= $feedback->type === 'complaint' ? 'selected' : '' ?>>Complaint</option>
            <option value="compliment" <?= $feedback->type === 'compliment' ? 'selected' : '' ?>>Compliment</option>
            <option value="question" <?= $feedback->type === 'question' ? 'selected' : '' ?>>Question</option>
            <option value="suggestion" <?= $feedback->type === 'suggestion' ? 'selected' : '' ?>>Suggestion</option>
        </select>
    </div>

    <div>
        <h3 class="text-xl">Avaliação *</h3>
        <div class=" flex justify-between w-48">
            <label for="rating-one">1</label>
            <input type="radio" name="feedback[rating]" id="rating-one" value="1"
                <?= $feedback->rating === 1 ? 'checked' : '' ?>>

            <label for="rating-two">2</label>
            <input type="radio" name="feedback[rating]" id="rating-two" value="2"
                <?= $feedback->rating === 2 ? 'checked' : '' ?>>

            <label for="rating-three">3</label>
            <input type="radio" name="feedback[rating]" id="rating-three" value="3"
                <?= $feedback->rating === 3 ? 'checked' : '' ?>>

            <label for="rating-four">4</label>
            <input type="radio" name="feedback[rating]" id="rating-four" value="4"
                <?= $feedback->rating === 4 ? 'checked' : '' ?>>

            <label for="rating-five">5</label>
            <input type="radio" name="feedback[rating]" id="rating-five" value="5"
                <?= $feedback->rating === 5 ? 'checked' : '' ?>>
        </div>
    </div>

    <div>
        <h2 class="text-xl">Descrição *</h2>
        <textarea name="message[content]" id="message_content" class="bg-tertiary rounded p-2"></textarea>
    </div>

    <div>
        <h2 class="text-xl">Faz mal a saúde *</h2>
        <label for="is-harmfull-yes" class="text-xl">Sim</label>
        <input type="radio" name="feedback[is_harmfull]" id="is-harmfull-yes" value="1"
            <?= $feedback->is_harmfull === 1 ? 'checked' : '' ?>>

        <label for="is-harmfull-no" class="text-xl">Não</label>
        <input type="radio" name="feedback[is_harmfull]" id="is-harmfull-no" value="0"
            <?= $feedback->is_harmfull === 0 ? 'checked' : '' ?>>
    </div>

    <button type="submit" class="bg-primary w-20 h-9 rounded">Salvar</button>
</form>