<div class="flex flex-col items-center w-4/5 mx-auto min-h-screen">
    <a href="<?= Route(name: 'user.feedbacks.new') ?>" class="btn-md bg-primary text-white px-4 py-2 rounded mb-10 block text-center">NOVO</a>

    <?php foreach ($openFeedbacks as $feedback): ?>
        <div class="flex justify-between items-center bg-tertiary text-white p-4 rounded shadow-md mb-4 w-full max-w-md">
            <span class="w-3 h-3 bg-white rounded-full mr-3"></span>
            <h2 class="text-lg font-bold"><?= $feedback->type ?></h2>
            <div class="flex">
                <form
                    method="POST">
                    <input type="hidden" name="_method" value="UPDATE">
                    <button type="submit" class="px-4 py-2 rounded"><i class="fa-regular fa-pen-to-square text-lg leading-none"></i></button>
                </form>
                <form
                    action="
                    <?=
                    Route(
                        name: 'user.feedbacks.delete',
                        params: ['id' => $feedback->id]
                    )
                    ?>"
                    method="POST">
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="px-4 py-2 rounded text-red-500"><i class="fa-regular fa-trash-can text-lg leading-none"></i></button>
                </form>
            </div>
            <a href="<?= route('user.feedbacks.edit', params: ['id' => $feedback->id]) ?>">
                Editar 2
            </a>
        </div>
    <?php endforeach; ?>
</div>