<h1 
    class="text-center w-full rf-2xl pb-0 font-ws text-primary/75 font-bold mb-6 pt-4"
>
    <?= $title ?>
</h1>

<div class="mt-4 mx-2 mb-28">
    <?php foreach($goods as $good): ?>
        <div class="card mb-8">
            <div class="card-header bg-secondary">
                <h2 class="card-title text-white"><?= $good->description ?></h2>
                <div class="flex justify-center items-center">
                    <!-- Edit -->
                    <a 
                        href="<?= Route(
                            name: 'admin.snackbar_good.edit', 
                            params: ['id' => $good->id]
                        ) ?>"
                    >
                        <i class="card-icon text-tertiary fa-regular fa-pen-to-square text-lg leading-none"></i>
                    </a>
                    <!-- Delete -->
                    <form
                        action="<?= Route(name: 'admin.snackbar.destroy', params: ['id' => $good->id]) ?>"
                        method="POST" class="flex items-center mb-0 q">
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="px-4 py-2 rounded text-red-500 inline-flex items-center">
                            <i class="fa-regular fa-trash-can text-lg leading-none"></i>
                        </button>
                    </form>
                    <!--  -->
                </div>
            </div>
            <div class="card-body">
                <p id="snackbar-card-<?= $good->id ?>" class="card-content rf-lg font-bold text-secondary text-center">
                <?= price_format(value: $good->price) ?>
                </p>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<a
    href="<?= Route(name: 'admin.snackbar.new') ?>"
    class="btn-round bg-primary text-white fixed bottom-8 right-8">
    <i class="fa-solid fa-plus"></i>
</a>

<button id="refresh-data" class="btn-round bg-primary text-white fixed bottom-8 left-8">
    <i class="fa-solid fa-arrows-rotate"></i>
</button>