<html 
    lang="pt-br"
>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RU</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/styles.css" />

</head>

<body class="min-h-svh">
    <?php require '_flash_message.phtml'; ?>

    <nav class="grid grid-cols-2 h-1/10 bg-primary shadow-lg">
        <?php if (!is_home_page()): ?>
            <a 
            href="javascript:history.back()"
            class="justify-self-start self-center"
            >
                <i 
                    class="fa-solid fa-left-long px-6 text-4xl text-white"
                ></i>
            </a>
        <?php endif; ?>

        <i 
            class="fa-solid fa-bars px-6 text-4xl text-white justify-self-end self-center col-start-2" 
            id="open-menu"
        ></i>

        <ul 
            class="hidden absolute h-screen w-4/5 bg-secondary top-0 right-0 px-8 py-4 flex-col justify-start items-start gap-4" 
            id="menu-list"
        >
            <li id="close-menu" class="flex items-center gap-2 text-white">
                <i class="fa-solid fa-xmark text-2xl"></i>
            </li>
            <li class="flex items-center gap-2 text-white">
                <i class="fa-regular fa-circle-user text-2xl"></i>
                <p>Perfil</p>
            </li>
            <li class="flex items-center gap-2 text-white">
                <a class="flex items-center gap-2" 
                    href="<?= route('feedbacks') ?>">
                    <i class="fa-regular fa-message text-2xl"></i>
                    <p>Avaliações</p>
                </a>
            </li>
            <li class="flex items-center gap-2 text-white">
                <i class="fa-regular fa-message text-2xl"></i>
                <p>Cardápio</p>
            </li>
            <li class="flex items-center gap-2 text-white">
                <a class="flex items-center gap-2" 
                    href="<?= route('logout') ?>"
                >
                    <i class="fa-solid fa-arrow-right-from-bracket text-2xl"></i>
                    <p>Sair</p>
                </a>
            </li>
        </ul>
    </nav>

    <?php require $view ?>
</body>

<script src="/assets/js/Controllers/admin.js" type="module"></script>

</html>