<!-- <html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rastreador de Problemas</title>

    <script src="/assets/js/application.js"></script>

    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body class="">
    <?php require '_flash_message.phtml'; ?>

    <?php require $view ?>
</body>

</html> -->