<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RU</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/application.css" />
    <link rel="stylesheet" href="/assets/css/homeUser.css">

</head>

<body class="">
    <?php require '_flash_message.phtml'; ?>

    <?php require $view ?>
</body>

</html>
<script src="/assets/js/admin.js"></script>