<html 
    lang="pt-br"
    class="bg-[url('/assets/images/background/backgrounf.jpg')] bg-cover bg-no-repeat"
>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RU</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <link rel="stylesheet" href="/assets/css/application.css" />
</head>

<body class="">
    <?php require $view ?>
    
    <?php require '_flash_message.phtml'; ?>
</body>

<script src="/assets/js/Controllers/login.js" type="module"></script>

</html>