<html 
    lang="pt-br"
    class="bg-[url('/assets/images/background/backgrounf.jpg')] bg-cover bg-no-repeat"
>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RU</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/styles.css" />

</head>

<body class="">
    <?php require '_flash_message.phtml'; ?>

<nav class="flex items-center justify-end h-1/10"
    >
        <i 
            class="fa-solid fa-bars px-6 text-4xl text-white flex items-center" 
            id="open-menu"
        ></i>

        <ul 
            class="hidden absolute h-screen w-4/5 bg-secondary top-0 px-8 py-4 flex-col justify-start items-start gap-4" 
            id="menu-list"
        >
            <li id="close-menu" class="flex items-center gap-2 text-white">
                <i class="fa-solid fa-xmark text-2xl"></i>
            </li>
            <li class="flex items-center gap-2 text-white">
                <i class="fa-regular fa-circle-user text-2xl"></i>
                <p>Perfil</p>
            </li>
            <li class="flex items-center gap-2 text-white">
                <a class="flex items-center gap-2" 
                    href="<?= route('user.feedbacks') ?>">
                    <i class="fa-regular fa-message text-2xl"></i>
                    <p>Feedback's</p>
                </a>
            </li>
            <li class="flex items-center gap-2 text-white">
                <a class="flex items-center gap-2" 
                    href="<?= route('logout') ?>">
                    <i class="fa-solid fa-arrow-right-from-bracket text-2xl"></i>
                    <p>Sair</p>
                </a>
            </li>
        </ul>
    </nav>

    <?php require $view ?>
</body>

<script src="/assets/js/Controllers/user.js" type="module"></script>

</html>